'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import type { FormField, FormFieldType, FormInput } from './types';
const types: FormFieldType[] = ['text', 'number', 'date', 'file', 'select', 'email', 'boolean'];
const fresh = (): FormField => ({ id: crypto.randomUUID(), label: '', type: 'text', required: false });
export function FormBuilder({ initial, onSave, pending }: { initial?: FormInput; onSave(input: FormInput): void; pending?: boolean }) {
  const [title, setTitle] = useState(initial?.title ?? ''); const [description, setDescription] = useState(initial?.description ?? ''); const [fields, setFields] = useState<FormField[]>(initial?.fields ?? []); const [error, setError] = useState('');
  function save(e: React.FormEvent) { e.preventDefault(); const trimmed = title.trim(); if (!trimmed) return setError('A title is required.'); for (const field of fields) { if (!field.label.trim()) return setError('Every field needs a label.'); if (field.type === 'select' && (!field.options?.length || new Set(field.options.map((option) => option.trim())).size !== field.options.length || field.options.some((option) => !option.trim()))) return setError('Select options must be unique and nonempty.'); if (field.condition && (field.condition.fieldId === field.id || !fields.some((candidate) => candidate.id === field.condition!.fieldId))) return setError('Conditions must reference another field.'); } setError(''); onSave({ title: trimmed, description: description.trim() || undefined, fields }); }
  const update = (index: number, value: Partial<FormField>) => setFields((all) => all.map((field, i) => i === index ? { ...field, ...value } : field));
  return <form onSubmit={save} className="grid gap-5"><label className="grid gap-1 text-sm font-medium">Title<input required className="h-10 rounded-md border bg-background px-3" value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="grid gap-1 text-sm font-medium">Description (optional)<input className="h-10 rounded-md border bg-background px-3" value={description} onChange={(e) => setDescription(e.target.value)} /></label><fieldset className="grid gap-3"><legend className="font-semibold">Fields</legend>{fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Label<input className="h-9 rounded border px-2" value={field.label} onChange={(e) => update(index, { label: e.target.value })} /></label><label className="grid gap-1 text-sm">Type<select className="h-9 rounded border px-2" value={field.type} onChange={(e) => update(index, { type: e.target.value as FormFieldType, options: e.target.value === 'select' ? field.options ?? [''] : undefined })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={field.required} onChange={(e) => update(index, { required: e.target.checked })} /> Required</label>{field.type === 'select' ? <label className="grid gap-1 text-sm">Options (one per line)<textarea className="rounded border p-2" value={(field.options ?? []).join('\n')} onChange={(e) => update(index, { options: e.target.value.split('\n') })} /></label> : null}<div className="flex items-end gap-2"><Button type="button" variant="outline" onClick={() => setFields((all) => all.filter((_, i) => i !== index))}>Remove</Button><Button type="button" variant="outline" disabled={index === 0} onClick={() => setFields((all) => { const copy = [...all]; [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]]; return copy; })}>Move up</Button></div></div>)}</fieldset><Button type="button" variant="outline" onClick={() => setFields((all) => [...all, fresh()])}>Add field</Button>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<Button disabled={pending}>{pending ? 'Saving…' : 'Save draft'}</Button></form>;
}
