'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useMemo } from 'react';
import { useAuth } from '@/components/providers/auth-provider';
import { Button } from '@/components/ui/button';
import { getApiScope } from '@/lib/api-client';
import { AsyncState, LoadingState } from '@/shared/components/async-state';
import { PageHeader, PageShell } from '@/shared/components/page';
import { canRetry, communicationKeys, listCommunications, retryCommunication } from './api';
import { statusLabels, typeLabels, type CommunicationFilters, type DeliveryStatus } from './types';

export function CommunicationsPage() { const { user, hasCapability } = useAuth(); const scope = getApiScope(user?.id); const router = useRouter(), pathname = usePathname(), search = useSearchParams(), client = useQueryClient(); const filters = useMemo<CommunicationFilters>(() => ({ candidateId: Number(search.get('candidateId')) || undefined, applicationId: Number(search.get('applicationId')) || undefined, status: (search.get('status') || undefined) as DeliveryStatus | undefined }), [search]); const result = useQuery({ queryKey: communicationKeys.list(scope, filters), queryFn: ({ signal }) => listCommunications(filters, signal), staleTime: 15_000, retry: false, refetchInterval: (q) => q.state.data?.some((m) => m.status === 'queued' || m.status === 'sending') ? 8_000 : false }); const retry = useMutation({ mutationFn: retryCommunication, onSuccess: () => void client.invalidateQueries({ queryKey: communicationKeys.all(scope) }) }); const setStatus = (status?: string) => { const next = new URLSearchParams(search.toString()); if (status) next.set('status', status); else next.delete('status'); router.replace(next.size ? `${pathname}?${next}` : pathname); };
return <PageShell><PageHeader title="Communications" description="Authorized delivery history. Queued means accepted for asynchronous delivery, not sent." actions={hasCapability('communications:templates:read') ? <Link className="rounded-md border px-3 py-2 text-sm" href="/communications/templates">Templates</Link> : undefined} /><div className="mb-4 flex gap-2"><label className="text-sm">Status <select className="ml-2 h-9 rounded-md border bg-background px-2" value={filters.status ?? ''} onChange={(e) => setStatus(e.target.value || undefined)}><option value="">All</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><Button variant="outline" onClick={() => void result.refetch()}>Refresh</Button></div>{result.isPending ? <LoadingState label="Loading communications" /> : result.isError ? <AsyncState kind="error" title="Communications could not be loaded" action={{ label: 'Retry', onClick: () => void result.refetch() }} /> : <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="p-3">Recipient</th><th className="p-3">Type</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{result.data.length ? result.data.map((m) => <tr className="border-b last:border-0" key={m.id}><td className="p-3"><div>{m.recipient}</div><div className="text-xs text-muted-foreground">{m.subject}</div></td><td className="p-3">{typeLabels[m.type]}</td><td className="p-3">{statusLabels[m.status]}{m.attempts > 1 ? ' · Retried' : ''}</td><td className="p-3"><time dateTime={m.createdAt}>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(m.createdAt))}</time></td><td className="p-3">{hasCapability('communications:retry') && canRetry(m.status) ? <Button size="sm" variant="outline" disabled={retry.isPending} onClick={() => { if (window.confirm(`Retry the ${typeLabels[m.type].toLowerCase()} to ${m.recipient}?`)) retry.mutate(m.id); }}>Retry</Button> : null}</td></tr>) : <tr><td className="p-6 text-center text-muted-foreground" colSpan={5}>No communications match these filters.</td></tr>}</tbody></table></div>}{retry.isError ? <p className="mt-3 text-sm text-destructive" role="alert">Retry could not be queued. Refresh to see the latest state.</p> : null}</PageShell>; }
