'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useAuth } from '@/components/providers/auth-provider';
import { Button } from '@/components/ui/button';
import { getApiScope } from '@/lib/api-client';
import { AsyncState, LoadingState } from '@/shared/components/async-state';
import { PageHeader, PageShell } from '@/shared/components/page';
import { communicationKeys, createTemplate, listTemplates } from './api';

export function TemplatesPage() { const { user, hasCapability } = useAuth(); const scope = getApiScope(user?.id), client = useQueryClient(); const templates = useQuery({ queryKey: communicationKeys.templates(scope), queryFn: ({ signal }) => listTemplates(signal), staleTime: 30_000, retry: false }); const [open, setOpen] = useState(false), [key, setKey] = useState(''), [name, setName] = useState(''), [subject, setSubject] = useState(''), [htmlBody, setHtmlBody] = useState(''); const publish = useMutation({ mutationFn: createTemplate, onSuccess: async () => { await client.invalidateQueries({ queryKey: communicationKeys.templates(scope) }); setOpen(false); setKey(''); setName(''); setSubject(''); setHtmlBody(''); } }); if (!hasCapability('communications:templates:read')) return <PageShell><AsyncState kind="forbidden" title="Template access is unavailable" /></PageShell>;
return <PageShell><PageHeader title="Email templates" description="Versions are immutable. Publishing the same key creates the next active version." actions={hasCapability('communications:templates:create') ? <Button onClick={() => setOpen((v) => !v)}>{open ? 'Close' : 'New version'}</Button> : undefined} />{open ? <form className="mb-6 grid gap-3 rounded-xl border bg-card p-5" onSubmit={(e) => { e.preventDefault(); publish.mutate({ key: key.trim(), name: name.trim(), subject: subject.trim(), htmlBody }); }}><label className="grid gap-1 text-sm">Stable key<input required minLength={2} maxLength={80} className="h-9 rounded-md border bg-background px-3" value={key} onChange={(e) => setKey(e.target.value)} /></label><label className="grid gap-1 text-sm">Name<input required minLength={2} maxLength={120} className="h-9 rounded-md border bg-background px-3" value={name} onChange={(e) => setName(e.target.value)} /></label><label className="grid gap-1 text-sm">Subject<input required maxLength={240} className="h-9 rounded-md border bg-background px-3" value={subject} onChange={(e) => setSubject(e.target.value)} /></label><label className="grid gap-1 text-sm">HTML content<textarea required className="min-h-36 rounded-md border bg-background p-3 font-mono" value={htmlBody} onChange={(e) => setHtmlBody(e.target.value)} /></label><p className="text-xs text-muted-foreground">Preview is intentionally unavailable here: authored HTML is never inserted into the application DOM.</p><div><Button disabled={publish.isPending}>Publish immutable version</Button></div>{publish.isError ? <p className="text-sm text-destructive" role="alert">The template could not be published. Check the fields and try again.</p> : null}</form> : null}{templates.isPending ? <LoadingState label="Loading templates" /> : templates.isError ? <AsyncState kind="error" title="Templates could not be loaded" action={{ label: 'Retry', onClick: () => void templates.refetch() }} /> : <div className="grid gap-3">{templates.data.map((template) => <article className="rounded-xl border bg-card p-5" key={template.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{template.name}</h2><p className="mt-1 text-sm text-muted-foreground">{template.key} · Version {template.version}</p></div><span className="rounded-full border px-2 py-1 text-xs">{template.active ? 'Active' : 'Historic'}</span></div><p className="mt-3 text-sm">{template.subject}</p></article>) || <AsyncState kind="empty" title="No templates yet" description="Publish the first template version when it is ready." />}</div>}</PageShell>; }
